questions/urls.py
from django.conf.urls import url
from .views import (question_list, 
                    question_detail, 
                    question_ask, 
                    question_update, 
                    category_list, 
                    category,
                    answer_update,
                    question_delete,
                    answer_delete,
                    notification)


urlpatterns = [
    url(r'^$', question_list, name='question_list'),
    url(r'^ask/$', question_ask, name='question_ask'),
    url(r'^notifications/$', notification, name='notification'),
    url(r'^categories/$', category_list, name='category_list'),
    url(r'^categories/(?P<slug>[\w-]+)/$', category, name='category'),
    url(r'^(?P<slug>[\w-]+)/delete/$', question_delete, name='question_delete'),
    url(r'^(?P<slug>[\w-]+)/edit/$', question_update, name='question_update'),
    url(r'^(?P<slug>[\w-]+)/answer/(?P<pk>\d+)/edit/$', answer_update, name='answer_update'),
    url(r'^(?P<slug>[\w-]+)/answer/(?P<pk>\d+)/delete/$', answer_delete, name='answer_delete'),
    url(r'^(?P<slug>[\w-]+)/$', question_detail, name='question_detail'),
]

yourquery/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from accounts.views import (login_view, 
                            register_view, 
                            logout_view, 
                            user_profile, 
                            user_profile_update)
from contact.views import contact
from core.views import home, about


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #Core
    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
    #Accounts
    url(r'^profile/(?P<username>\w+)/$', user_profile, name='user_profile'),
    url(r'^profile/(?P<username>\w+)/edit/$', user_profile_update, name='user_profile_update'),
    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
    #Contact
    url(r'^contact/$', contact, name='contact'),
    #Questions
    url(r'^questions/', include('questions.urls', namespace='questions')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

questions/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.
User = settings.AUTH_USER_MODEL


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True, verbose_name="category")
    slug = models.SlugField(unique=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("questions:category", kwargs={"slug": self.slug})




class Question(models.Model):
    user = models.ForeignKey(User)
    category = models.ForeignKey(Category)
    qus = models.CharField(max_length=256, verbose_name="question")
    details = models.TextField(blank=True)
    slug = models.SlugField(unique=True, max_length=256)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.qus

    def get_absolute_url(self):
        return reverse("questions:question_detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ['-updated', '-created']

    def _get_unique_slug(self):
        slug = slugify(self.qus)
        unique_slug = slug
        num = 1
        while Question.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug
 
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super(Question, self).save()


class Answer(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    ans = models.TextField(verbose_name="answer")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.question.qus

    class Meta:
        ordering = ['-updated', '-created']


class SendNotification(models.Model):
    user = models.ForeignKey(User, related_name='user')
    from_user = models.ForeignKey(User, related_name='from_user')
    question = models.ForeignKey(Question)
    message = models.CharField(max_length=256)
    sent = models.DateTimeField(auto_now_add=True)
    viewed = models.BooleanField(default=False)

    def __unicode__(self):
        return self.question.qus

    class Meta:
        ordering = ['-sent']

questions/forms.py
from django import forms
from .models import Question, Answer



class QuestionForm(forms.ModelForm):
     details=forms.Textarea()

     class Meta:
        model = Question
        fields = ["qus", "details", "category"]


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ["ans"]

questions/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from .forms import QuestionForm, AnswerForm
from .models import Category, Question, Answer, SendNotification
# Create your views here.


def question_list(request):
    queryset = Question.objects.all()

    query = request.GET.get("q")   
    if query:
        queryset = queryset.filter(
            Q(qus__icontains=query)|
            Q(category__name__icontains=query)
            ).distinct()

    paginator = Paginator(queryset, 12)
    page = request.GET.get("page")
    try:
        query_list = paginator.page(page)
    except PageNotAnInteger:
        query_list = paginator.page(1)
    except EmptyPage:
        query_list = paginator.page(paginator.num_pages)

    context = { "query_list": query_list }
    return render(request, "questions/question_list.html", context)


def question_detail(request, slug=None):
    question = get_object_or_404(Question, slug=slug)
    answers_list = Answer.objects.filter(question=question)
    context = { "question": question,
                "answers_list": answers_list,
                 }
    if request.user.is_authenticated:
        form = AnswerForm(request.POST or None)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.user = request.user
            answer.question = question
            answer.save()
            messages.success(request, 'Answer was Posted.')
            form = AnswerForm()    
        context = { "question": question,
                    "form": form,
                    "answers_list": answers_list,
                  }
    return render(request, "questions/question_detail.html", context)


@login_required()
def question_ask(request):
    form = QuestionForm(request.POST or None)
    if form.is_valid():
        question = form.save(commit=False)
        question.user = request.user
        question.save()
        messages.success(request, 'Question was Posted.')
        return redirect(question.get_absolute_url())
    context = { "form": form,
                "title": "Ask Question"
              }
    return render(request, "questions/ask.html", context)


@login_required()
def question_update(request, slug=None):
    instance = get_object_or_404(Question, slug=slug)
    if instance.user != request.user:
        raise Http404
    else:
        form = QuestionForm(request.POST or None, instance=instance)
        if form.is_valid():
            question = form.save(commit=False)
            question.user = request.user
            question.save()
            messages.success(request, 'Question was Updated.')
            return redirect(question.get_absolute_url())
        context = { "form": form,
                    "title": "Edit Question"
                    }
    return render(request, "questions/ask.html", context)


@login_required()
def question_delete(request, slug=None):
    question = get_object_or_404(Question, slug=slug)
    if not request.user.is_authenticated:
        raise Http404 
    else:
        if question.user != request.user:
            raise Http404
        else:
            question.delete() 
            messages.error(request, 'Question was Deleted.')
            return redirect(request.user.get_absolute_url()) 


@login_required()
def answer_update(request, slug=None, pk=None):
    question = get_object_or_404(Question, slug=slug)
    instance = get_object_or_404(Answer, pk=pk)
    if instance.user != request.user:
        raise Http404
    else:
        form = AnswerForm(request.POST or None, instance=instance)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.user = request.user
            answer.question = question
            answer.save()
            messages.success(request, 'Answer was Updated.')
            return redirect(question.get_absolute_url())
        context = { "form": form,
                    "title": "Update Answer"
                    }
    return render(request, "questions/answer.html", context)


@login_required()
def answer_delete(request, slug=None, pk=None):
    question = get_object_or_404(Question, slug=slug)
    answer = get_object_or_404(Answer, pk=pk)
    if not request.user.is_authenticated:
        raise Http404 
    else:
        if answer.user != request.user:
            raise Http404
        else:
            answer.delete() 
            messages.error(request, 'Answer was Deleted.')
            return redirect(question.get_absolute_url())


def category_list(request):
    categories = Category.objects.all()
    context = { "categories": categories }
    return render(request, "questions/category_list.html", context)


def category(request, slug=None):
    category = get_object_or_404(Category, slug=slug)   
    queryset = category.question_set.all()

    query = request.GET.get("q")   
    if query:
        queryset = queryset.filter(
            Q(qus__icontains=query)
            ).distinct()

    paginator = Paginator(queryset, 12)
    page = request.GET.get("page")
    try:
        query_list = paginator.page(page)
    except PageNotAnInteger:
        query_list = paginator.page(1)
    except EmptyPage:
        query_list = paginator.page(paginator.num_pages)
        
    context = { "query_list": query_list,
                "category": category
              }
    return render(request, "questions/category.html", context)


@login_required()
def notification(request):
    user = request.user
    notification = SendNotification.objects.filter(user=user)
    notification.update(viewed=True)

    paginator = Paginator(notification, 12)
    page = request.GET.get("page")
    try:
        query_list = paginator.page(page)
    except PageNotAnInteger:
        query_list = paginator.page(1)
    except EmptyPage:
        query_list = paginator.page(paginator.num_pages)

    context = { "query_list": query_list }
    return render(request, "questions/notification.html", context)

questions/templates/questions/answer.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | {{ block.super }}{% endblock title %}

{% block tinymce %} 
    {{ form.media }}
{% endblock tinymce %}

{% block content %}
<h2>{{ title }}</h2><hr>
<form method="POST" action="" >
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input class="btn btn-success" type="submit" value='Submit'>
</form>
{% endblock content %}

questions/templates/questions/ask.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | {{ block.super }}{% endblock title %}

{% block content %}
<h2>{{ title }}</h2><hr>
<form method="POST" action="" >
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input class="btn btn-success" type="submit" value='Submit'>
</form>
{% endblock content %}

questions/templates/questions/category.html
{% extends "core/base.html" %}

{% block title %} {{ category }} Questions | {{ block.super }}{% endblock title %}

{% block content %}

{% include "core/search.html" %}

<a class="btn btn-success" href="{% url 'questions:question_ask' %}">Ask your Questions</a>
<hr>

<h1>{{ category }} Questions</h1>
<hr>

{% for question in query_list %}
<div class="list-group">
  <div class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h4 class="mb-1"><b><a href="{{question.get_absolute_url}}" >{{ question.qus }}</a></b>
      <small>Asked {{ question.updated|timesince }} ago By <b>
      <a href="{{question.user.get_absolute_url}}" >{{ question.user.username }}</a>
      </b></small></h4>
      <small><b>Category:</b> <a href="{{question.category.get_absolute_url}}" >{{ question.category }}</a></small>
    </div>
    <p class="mb-1">{{ question.details|linebreaks|truncatechars:120 }}</p>

  </div>
</div>
{% endfor %}

{% include "core/paginator.html" %}

{% endblock content %}

questions/templates/questions/category_list.html
{% extends "core/base.html" %}

{% block title %} Categories | {{ block.super }}{% endblock title %}

{% block content %}
<div class="container">
    <h2>Categories</h2>
    <hr>
<div>
<div class="list-group">
{% for obj in categories %}
  <a href="{{ obj.get_absolute_url }}" class="list-group-item">{{obj.name}}</a>
{% endfor %}
</div>
{% endblock content %}

questions/templates/questions/notification.html
{% extends "core/base.html" %}

{% block title %} Notifications | {{ block.super }}{% endblock title %}

{% block content %}

<h1>Notifications</h1>
<hr>
{% if query_list %}

{% for obj in query_list %}
    <div class="list-group">
    <a href="{{ obj.question.get_absolute_url }}" class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h4 class="mb-1"><b>{{ obj.message }} for "{{ obj.question }}"</b></h4>
        {{ obj.sent|timesince }} ago from <b>{{ obj.from_user }}</b>
    </div>
    <p class="mb-1">{{ question.details|linebreaks|truncatechars:120 }}</p>

  </a>
</div>

{% endfor %}

{% else %}

No Notifications Found.

{% endif %}

{% include "core/paginator.html" %}

{% endblock content %}

questions/templates/questions/question_detail.html
{% extends "core/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Question Details | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}
<h2>{{ question.qus }}
<small>Asked by <a href="{{question.user.get_absolute_url}}">{{ question.user.username }}</a></small>
{% if request.user == question.user %}
<span style="float: right;">
<a class="btn btn-success btn-sm" href="{{question.get_absolute_url}}edit/" role="button">Edit</a>
<a class="btn btn-danger btn-sm" href="{{question.get_absolute_url}}delete/" role="button">Delete</a>
</span>
{% endif %}
</h2> 
<hr>
<b>Created: </b>{{ question.created }}<br>
<b>Updated: </b>{{ question.updated }}<br>
<b>Category: </b><a href="{{question.category.get_absolute_url}}">{{ question/Category/get_absolute_url }}</a>
<hr>
<strong>Details</strong>
<hr>
<p>{{ question.details }}</p>
<hr>

{% if request.user.is_authenticated %}
<form method="POST" action="" >
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-success" type="submit" value='Submit'>
</form>
<hr>
{% endif %}

<div class="container">

    <div class="row">

        <div class="col-sm-12">

            <h2>Answers:</h2>

        </div><!-- /col-sm-12 -->

    </div><!-- /row -->

    <hr>

    {% for answer in answers_list %}

        {% if answer.user.picture %}
        <div class="col-sm-1">

            <div class="thumbnail">

                <img class="img-responsive user-photo" src="{{ answer.user.picture.url }}">

            </div><!-- /thumbnail -->

        </div><!-- /col-sm-1 -->
        {% else %}
                <div class="col-sm-1">
                <h4 align="center"><small>No <br>Image</small></h4>
        </div><!-- /col-sm-1 -->
        {% endif %}

        <div class="col-sm-11">

            <div class="panel panel-default">

                <div class="panel-heading">
                    <strong>
                    <a href="{{answer.user.get_absolute_url}}">{{ answer.user.username }}</a>
                    </strong>
                    <span style="padding-left: 5px;" >
                    {% if request.user == answer.user %}
                        (<a href="{% url 'questions:answer_update' slug=answer.question.slug pk=answer.pk %}">Edit</a>&nbsp;/
                        <a href="{% url 'questions:answer_delete' slug=answer.question.slug pk=answer.pk %}">Delete</a>)
                    {% endif %}
                    </span> 
                    <span style="float: right;" class="text-muted">
                    {{ answer.updated|timesince }} ago
                    </span>

                </div>

                <div class="panel-body">
                    {{ answer.ans }}
                </div><!-- /panel-body -->

            </div><!-- /panel panel-default -->

            <hr>

        </div><!-- /col-sm-5 -->
  {% endfor %}
</div><!-- /container -->

{% endblock content %}

questions/templates/questions/question_list.html
{% extends "core/base.html" %}

{% block title %} Questions | {{ block.super }}{% endblock title %}

{% block content %}

{% include "core/search.html" %}

<a class="btn btn-success" href="{% url 'questions:question_ask' %}">Ask your Questions</a>
<hr>

<h1>All Questions</h1>
<hr>
{% for question in query_list %}
<div class="list-group">
  <div class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h4 class="mb-1"><b><a href="{{question.get_absolute_url}}" >{{ question.qus }}</a></b>
      <small>Asked {{ question.updated|timesince }} ago By <b>
      <a href="{{question.user.get_absolute_url}}" >{{ question.user.username }}</a>
      </b></small></h4>
      <small><b>Category:</b> <a href="{{question.category.get_absolute_url}}" >{{ question.category }}</a></small>
    </div>
    <p class="mb-1">{{ question.details|linebreaks|truncatechars:120 }}</p>

  </div>
</div>
{% endfor %}

{% include "core/paginator.html" %}

{% endblock content %}