questions/urls.py
from django.conf.urls import url
from .views import (question_list, 
                    question_detail, 
                    question_ask, 
                    question_update, 
                    category_list, 
                    category,
                    answer_update,
                    question_delete,
                    answer_delete,
                    notification)


urlpatterns = [
    url(r'^$', question_list, name='question_list'),
    url(r'^ask/$', question_ask, name='question_ask'),
    url(r'^notifications/$', notification, name='notification'),
    url(r'^categories/$', category_list, name='category_list'),
    url(r'^categories/(?P<slug>[\w-]+)/$', category, name='category'),
    url(r'^(?P<slug>[\w-]+)/delete/$', question_delete, name='question_delete'),
    url(r'^(?P<slug>[\w-]+)/edit/$', question_update, name='question_update'),
    url(r'^(?P<slug>[\w-]+)/answer/(?P<pk>\d+)/edit/$', answer_update, name='answer_update'),
    url(r'^(?P<slug>[\w-]+)/answer/(?P<pk>\d+)/delete/$', answer_delete, name='answer_delete'),
    url(r'^(?P<slug>[\w-]+)/$', question_detail, name='question_detail'),
]

yourquery/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from accounts.views import (login_view, 
                            register_view, 
                            logout_view, 
                            user_profile, 
                            user_profile_update)
from contact.views import contact
from core.views import home, about


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #Core
    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
    #Accounts
    url(r'^profile/(?P<username>\w+)/$', user_profile, name='user_profile'),
    url(r'^profile/(?P<username>\w+)/edit/$', user_profile_update, name='user_profile_update'),
    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
    #Contact
    url(r'^contact/$', contact, name='contact'),
    #Questions
    url(r'^questions/', include('questions.urls', namespace='questions')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.urls import reverse

# Create your models here.
USERNAME_REGEX = '^[a-zA-Z0-9.+-]*$'
NAME_REGEX = '^[a-zA-Z]*$'


class User(AbstractUser):
    username = models.CharField(max_length=256, unique=True, blank=False,
                                validators=[
                                        RegexValidator(
                                        regex = USERNAME_REGEX,
                                        message = 'Username must be Alpahnumeric or contain any of the following: ".+ -" ',
                                        code='invalid_username'
                                        )]
                                )
    first_name = models.CharField(max_length=256, blank=False,
                                  validators=[
                                        RegexValidator(
                                        regex = NAME_REGEX,
                                        message = 'Name must be Alphabetic',
                                        code='invalid_first_name'
                                        )]
                                )
    last_name = models.CharField(max_length=256, blank=False,
                                  validators=[
                                        RegexValidator(
                                        regex = NAME_REGEX,
                                        message = 'Name must be Alphabetic',
                                        code='invalid_last_name'
                                        )]
                                )
    email = models.EmailField(unique=True, blank=False)
    bio = models.CharField(max_length=512, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    picture = models.ImageField(null=True, 
                                blank=True, 
                                default='img/default.png',
                                height_field="height_field", 
                                width_field="width_field",
                                verbose_name="profile picture"
                                )
    height_field = models.IntegerField(default=600, null=True)
    width_field = models.IntegerField(default=600, null=True)
    USERNAME_FIELD = 'email' # use email to log in
    REQUIRED_FIELDS = ['username'] # required when user is created

    def __unicode__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("user_profile", kwargs={"username": self.username})
    

questions/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.
User = settings.AUTH_USER_MODEL


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True, verbose_name="category")
    slug = models.SlugField(unique=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("questions:category", kwargs={"slug": self.slug})




class Question(models.Model):
    user = models.ForeignKey(User)
    category = models.ForeignKey(Category)
    qus = models.CharField(max_length=256, verbose_name="question")
    details = models.TextField(blank=True)
    slug = models.SlugField(unique=True, max_length=256)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.qus

    def get_absolute_url(self):
        return reverse("questions:question_detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ['-updated', '-created']

    def _get_unique_slug(self):
        slug = slugify(self.qus)
        unique_slug = slug
        num = 1
        while Question.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug
 
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super(Question, self).save()


class Answer(models.Model):
    user = models.ForeignKey(User)
    question = models.ForeignKey(Question)
    ans = models.TextField(verbose_name="answer")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.question.qus

    class Meta:
        ordering = ['-updated', '-created']


class SendNotification(models.Model):
    user = models.ForeignKey(User, related_name='user')
    from_user = models.ForeignKey(User, related_name='from_user')
    question = models.ForeignKey(Question)
    message = models.CharField(max_length=256)
    sent = models.DateTimeField(auto_now_add=True)
    viewed = models.BooleanField(default=False)

    def __unicode__(self):
        return self.question.qus

    class Meta:
        ordering = ['-sent']

accounts/forms.py
import datetime
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.forms.extras.widgets import SelectDateWidget
from .models import User


class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password")

        if email and password:
            user = authenticate(email=email, password=password)
            if not user:
                raise forms.ValidationError("User Does Not Exist.")
            if not user.check_password(password):
                raise forms.ValidationError("Password Does not Match.")
            if not user.is_active:
                raise forms.ValidationError("User is not Active.")

        return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegistrationForm(UserCreationForm):
    bio = forms.CharField(required=False, widget=forms.Textarea)
    birth_date = forms.DateField(widget=SelectDateWidget(years=range(1940, 2010)))
    class Meta:
        model = User
        fields = ("first_name",
                  "last_name", 
                  "username", 
                  "email", 
                  "birth_date", 
                  "bio", 
                  "picture", 
                  "password1", 
                  "password2" )

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.birth_date = self.cleaned_data['birth_date']
        user.bio = self.cleaned_data['bio']
        if commit:
            user.save()
        return user


class UserProfileUpdateForm(forms.ModelForm):
    bio = forms.CharField(required=False, widget=forms.Textarea)
    birth_date = forms.DateField(widget=SelectDateWidget(years=range(1940, 2010)))
    class Meta:
        model = User 
        fields = ("first_name", 
                  "last_name", 
                  "email", 
                  "bio", 
                  "birth_date", 
                  "picture")

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth import (authenticate,
                                 login,
                                 logout
                                )
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserLoginForm, UserRegistrationForm, UserProfileUpdateForm
from .models import User

# Create your views here.
def login_view(request): # users will login with their Email & Password
    if request.user.is_authenticated:
        return redirect("home")
    else:
        title = "Login"
        form = UserLoginForm(request.POST or None)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            # authenticates Email & Password
            user = authenticate(email=email, password=password) 
            login(request, user)
            return redirect("home")
        context = {"form":form,
                   "title":title
        }

        return render(request, "accounts/form.html", context)


def register_view(request): # Creates a New Account & login New users
    if request.user.is_authenticated:
        return redirect("home")
    else:
        title = "Register"
        form = UserRegistrationForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get("password1")
            user.set_password(password)
            user.save()
            new_user = authenticate(email=user.email, password=password)
            login(request, new_user)
            return redirect("home")

        context = {"title":title, "form":form}

        return render(request, "accounts/form.html", context)


def logout_view(request): # logs out the logged in users
    if not request.user.is_authenticated:
        return redirect("login")
    else:
        logout(request)
        return redirect("home")


def user_profile(request, username=None): # Displays User Profile
    user_profile = get_object_or_404(User, username=username)
    user_questions = user_profile.question_set.all()
    context = { "user_profile": user_profile, 
                "user_questions": user_questions 
              }
    return render(request, "accounts/profile.html", context)


@login_required()
def user_profile_update(request, username=None): # updates User profile
    instance = get_object_or_404(User, username=username)
    if request.user.username != instance.username:
        raise Http404
    else:
        form = UserProfileUpdateForm(request.POST or None, request.FILES or None, instance=instance)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            profile = form.save(commit=False)
            profile.email = email
            profile.save() # Saves the Updated Profile
            messages.success(request, 'Profile was Updated.')
            return redirect(profile.get_absolute_url())
        context = {
                  "form": form,
                  "title": "update"
                }
        return render(request, "accounts/profile_update.html", context)

accounts/templates/accounts/form.html
{% extends 'core/base.html' %}

{% load crispy_forms_tags %}

{% block title %} {{ title }} | {{ block.super }}{% endblock title %}

{% block content %}

<h1>{{ title }}</h1>
<hr>
<form method="POST" action="" enctype='multipart/form-data'>
	{% csrf_token %}
	{{ form|crispy }}
    <br>
	<input class="btn btn-success" type="submit" value='{{ title }}'>&nbsp; &nbsp;
    {% if request.path == "/login/" %}
    Don't Have an Account <a href="{% url 'register' %}">Register Here.</a>
    {% else %}
    Have an Account <a href="{% url 'login' %}">Login Here.</a>
    {% endif %}
</form>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'core/base.html' %}

{% block title %} Profile | {{ block.super }}{% endblock title %}

{% block content %}
{% include "core/messages.html" %}
<hr>
<div class="container bootstrap snippet">
    <div class="row">
        <div class="col-sm-10"><h1>{{ user_profile.first_name }} {{ user_profile.last_name }}</h1><hr>
        <b>Email: </b><a href="mailto:#">{{ user_profile.email }}</a><br>
        {% if user_profile.birth_date %}
        <small><b>Date of Birth:</b> {{ user_profile.birth_date }}</small><br>
        {% endif %}
        {% if request.user.username == user_profile.username %}
        <br>
        <a class="btn btn-success btn-sm" href="{{user_profile.get_absolute_url}}edit/" role="button">Edit</a>
        {% endif %}
        </div>

        {% if user_profile.picture %}
        <div class="col-sm-2"><a href="{{ user_profile.get_absolute_url }}" class="pull-right"><img title="profile image" class="img-circle img-responsive" src="{{ user_profile.picture.url }}"></a></div>
        {% endif %}
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-3"><!--left col-->
              
          <ul class="list-group">
            <li class="list-group-item text-muted">Profile</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Username</strong></span>{{ user_profile.username }}</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Joined</strong></span>{{ user_profile.date_joined|date:'d-m-Y' }}</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Last seen</strong></span>{{ user_profile.last_login|timesince }} ago</li>
          </ul> 
              
          <ul class="list-group">
            <li class="list-group-item text-muted">Activity <i class="fa fa-dashboard fa-1x"></i></li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Asked</strong></span> {{ user_profile.question_set.count }}</li>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Answered</strong></span> {{ user_profile.answer_set.count }}</li>
          </ul>  
        </div><!--/col-3-->

        <div class="col-sm-9">
          
          <ul class="nav nav-tabs" id="myTab">
          {% if user_profile.bio %} 
            <li class="active"><a href="#bio" data-toggle="tab">Bio</a></li>
            <li><a href="#questions" data-toggle="tab">Questions Asked</a></li>
            {% else %}
            <li class="active"><a href="#questions" data-toggle="tab">Questions Asked</a></li>
            {% endif %}
          </ul>
        
          <div class="tab-content">
          {% if user_profile.bio %} 
            <div class="tab-pane active" id="bio">
              <hr>
                <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Bio</h3>
                </div>
                    <div class="panel-body">
                        {{ user_profile.bio }}
                    </div>
                </div>

              
                <div class="row">
                  <div class="col-md-4 col-md-offset-4 text-center">
                    <ul class="pagination" id="myPager"></ul>
                  </div>

              </div><!--/table-resp-->
              {% endif %}
              
             </div><!--/tab-pane-->
             <div class="tab-pane" id="questions">
               <hr>
                <ul class="list-group">
                {% for question in user_questions %}
                    <li class="list-group-item text-right"><a href="{{question.get_absolute_url}}" class="pull-left">{{ question.qus }}</a> {{ question.updated|date:'d-m-Y' }}</li>
                {% endfor %}                 
                  
                </ul> 
               
             </div><!--/tab-pane-->

{% endblock content %}

accounts/templates/accounts/profile_update.html
{% extends 'core/base.html' %}

{% load crispy_forms_tags %}

{% block title %} Profile Update | {{ block.super }}{% endblock title %}

{% block content %}

<h1>Edit Profile</h1>
<hr>
<form method="POST" action="" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input class="btn btn-success" type="submit" value='{{ title }}'>
</form>

{% endblock content %}