questions/urls.py
from django.conf.urls import url
from .views import (question_list, 
                    question_detail, 
                    question_ask, 
                    question_update, 
                    category_list, 
                    category,
                    answer_update,
                    question_delete,
                    answer_delete,
                    notification)


urlpatterns = [
    url(r'^$', question_list, name='question_list'),
    url(r'^ask/$', question_ask, name='question_ask'),
    url(r'^notifications/$', notification, name='notification'),
    url(r'^categories/$', category_list, name='category_list'),
    url(r'^categories/(?P<slug>[\w-]+)/$', category, name='category'),
    url(r'^(?P<slug>[\w-]+)/delete/$', question_delete, name='question_delete'),
    url(r'^(?P<slug>[\w-]+)/edit/$', question_update, name='question_update'),
    url(r'^(?P<slug>[\w-]+)/answer/(?P<pk>\d+)/edit/$', answer_update, name='answer_update'),
    url(r'^(?P<slug>[\w-]+)/answer/(?P<pk>\d+)/delete/$', answer_delete, name='answer_delete'),
    url(r'^(?P<slug>[\w-]+)/$', question_detail, name='question_detail'),
]

yourquery/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from accounts.views import (login_view, 
                            register_view, 
                            logout_view, 
                            user_profile, 
                            user_profile_update)
from contact.views import contact
from core.views import home, about


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #Core
    url(r'^$', home, name='home'),
    url(r'^about/$', about, name='about'),
    #Accounts
    url(r'^profile/(?P<username>\w+)/$', user_profile, name='user_profile'),
    url(r'^profile/(?P<username>\w+)/edit/$', user_profile_update, name='user_profile_update'),
    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name='register'),
    url(r'^logout/$', logout_view, name='logout'),
    #Contact
    url(r'^contact/$', contact, name='contact'),
    #Questions
    url(r'^questions/', include('questions.urls', namespace='questions')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from questions.models import Question

# Create your views here.
def home(request):
    queryset = Question.objects.all()[:6]
    context = {"queryset": queryset}
    return render(request, "core/home.html", context)


def about(request):
    return render(request, "core/about.html", {})

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %} About | {{ block.super }}{% endblock title %}

{% block content %}

<h1>About US</h1>
<hr>
<p>png</p>

<p>Iumour and the like).
</p>


<p>Thham.</p>

{% endblock content %}

core/templates/core/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title %} RGM-QUORA {% endblock title %}</title>
    <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href='{% static "css/base.css" %}'>
        <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}'>
        <link rel="stylesheet" href='{% static "css/bootstrap-theme.min.css" %}'>
<!--         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->
    </head>
    <body>
        {% include "core/navbar.html" %}
            <div class="container" style="padding-top: 80px;" >
                {% block content %}

                {% endblock content %}
            </div>
        {% include "core/footer.html" %}

<!-- Latest compiled and minified JavaScript -->
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}" ></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>

<!--         <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->
    </body>
</html>

core/templates/core/footer.html
<hr>
<footer class="footer navbar-fixed">
    <!--Footer Links-->
    <div class="container-fluid">
        <div class="row">
            <!--First column-->
            <div class="col-md-6">
                <h4 class="title"><b>Footer Content</b></h4>
                <p> Here.</p>
            </div>
            <!--/.First column-->
            <!--Second column-->
            <div class="col-md-6">
                <h5 class="title"><b>Links</b></h5>

                <a href="{% url 'home' %}">Home </a>|
                <a href="{% url 'questions:question_list' %}">Questions</a> |&nbsp;
                <a href="{% url 'questions:category_list' %}">Categories</a> |&nbsp;
                <a href="{% url 'about' %}">About Us</a> |&nbsp;
                <a href="{% url 'contact' %}">Contact Us</a>

            </div>
            <!--/.Second column-->
        </div>
    </div>
    <!--/.Footer Links-->
    <!--Copyright-->
    <div class="footer-copyright">
        <div class="container-fluid">
            ©: <a href="http://127.0.0.1:8000/"> dasniel</a>
        </div>
    </div>
    <!--/.Copyright-->
</footer>
<br>

core/templates/core/home.html
{% extends "core/base.html" %}

{% block title %} Home | {{ block.super }}{% endblock title %}

{% block content %}
<div class="jumbotron">
  <h1>RGM-QUORA</h1>com</h1>
  <p>.</p>
  <p><a class="btn btn-primary btn-lg" href="{% url 'questions:question_list' %}" role="button">Questions</a>
  <a class="btn btn-default btn-lg" href="{% url 'contact' %}" role="button">Contact US</a></p>
</div>

<div class="container">
  <h2>New Questions</h2>
  <hr>
  <div>
    <div class="list-group">
      {% for question in queryset %}
      <div class="list-group">
        <div class="list-group-item list-group-item-action flex-column align-items-start">
          <div class="d-flex w-100 justify-content-between">
            <h4 class="mb-1"><b><a href="{{question.get_absolute_url}}" >{{ question.qus }}</a></b>
            <small>Asked {{ question.updated|timesince }} ago By <b>
            <a href="{{question.user.get_absolute_url}}" >{{ question.user.username }}</a>
            </b></small></h4>
            <small><b>Category:</b> <a href="{{question.category.get_absolute_url}}" >{{ question.category }}</a></small>
          </div>
          <p class="mb-1">{{ question.details|linebreaks|truncatechars:120 }}</p>

        </div>
      </div>
      {% endfor %}

    </div>
    <a href="{% url 'questions:question_list' %}">View All Items ---></a>
  </div>
</div>
{% endblock content %}

core/templates/core/messages.html
<!-- {% if messages %}

{% if messages.error %}

<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-success" role="alert" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</ul>

{% else %}

<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-danger" role="alert" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</ul>

{% endif %}

{% endif %} -->

{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

core/templates/core/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}" style="padding-left: 30px;">RGM-QUORA.com</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'home' %}">Home </a></li>
        <li><a href="{% url 'questions:question_list' %}">Questions</a></li>
        <li><a href="{% url 'questions:category_list' %}">Categories</a></li>
        <li><a href="{% url 'questions:question_ask' %}">Ask</a></li>
        <li><a href="{% url 'about' %}">About Us</a></li>
        <li><a href="{% url 'contact' %}">Contact Us</a></li> 
      </ul>
      
      <ul class="nav navbar-nav navbar-right" style="padding-right: 30px;">
        {% if request.user.is_authenticated %}
          {% if request.user.picture %}
            <li style="padding-top: 7px;"><img title="profile image" class="img-circle" src="{{ request.user.picture.url }}" id="nav-img"></li>
          {% endif %}
        <li class="dropdown">
          <a href="{{request.user.get_absolute_url}}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          {{ request.user.username }} 
          {% if not_viewed %}
          &nbsp;<span class="badge">{{ not_viewed }}</span>
          {% endif %}
          <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
              <li><a href="{{request.user.get_absolute_url}}">Profile</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'questions:notification' %}">Notifications &nbsp; &nbsp;<span class="badge">{{ not_viewed }}</span></a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'logout' %}">Logout</a></li>
          </ul>
        </li>
        {% else %}
        <li><a href="{% url 'login' %}">Login</a></li>
        <li><a href="{% url 'register' %}">Register</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

core/templates/core/paginator.html
<div style="float: right;">
<div class="pagination">
    <em class="step-links">
        {% if query_list.has_previous %}
            <a href="?page={{ query_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        &nbsp;<em class="current">
            Page {{ query_list.number }} of {{ query_list.paginator.num_pages }}.
        </em>&nbsp;

        {% if query_list.has_next %}
            <a href="?page={{ query_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </em>
</div>
</div>

core/templates/core/search.html
<div style="float: right;">
    <form method='GET' action=''>
        <input type='text' name='q' placeholder='Search' value='{{ request.GET.q }}'/>
        <input class="btn btn-primary" type='submit' value='Search' />
    </form>
</div>
<hr>
{% if request.GET.q %}

<p>showing search results for "{{ request.GET.q }}"</p><br>

{% endif %}